service:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - GITHUB_APP_ID=${GITHUB_APP_ID}
      - GITHUB_PRIVATE_KEY=${GITHUB_PRIVATE_KEY}
      - GITHUB_WEBHOOK_SECRET=${GITHUB_WEBHOOK_SECRET}
      - GITHUB_WEBHOOK_PATH=${GITHUB_WEBHOOK_PATH}
    # command: >
    #   sh -c "gunicorn -k uvicorn.workers.UvicornWorker main:app --host
    env_file:
      - .envrc
    networks: github-app-network

  smee:
    build:
      context: .
      dockerfile: Dockerfile.smee
    environment:
      - SMEE_URL=${SMEE_URL}
      - SMEE_TARGET=${SMEE_TARGET}
    env_file:
      - .envrc
    networks: github-app-network

networks:
  github-app-network:
    driver: bridge
