# docker build -f Dockerfile.deps -t nodejs-slim .
# docker run --rm -it -p nodejs-slim
FROM node:20-alpine

# https://github.com/probot/smee-client
RUN npm install -g smee-client

# Enable verbose logging with NODE_DEBUG
ENV NODE_DEBUG=smee

CMD ["sh", "-c", "smee --url $SMEE_URL --target $SMEE_TARGET"]
