# docker build -f Dockerfile.deps -t python-deps .
# docker run --rm -it -p python-deps
FROM python:3-slim

WORKDIR /app

# Copy python dependencies
COPY Pipfile Pipfile.lock ./

RUN pip install --root-user-action ignore pipenv
RUN pipenv install --deploy --ignore-pipfile
